version: '2.2'
services:
  golang:
    build: ./build
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - .:/go/src/github.com/eve-qunliu/articles
    working_dir: /go/src/github.com/eve-qunliu/articles

  postgres:
    image: postgres:9.6-alpine
    env_file: .env
    volumes:
      - .:/opt/app
